# Generated by Django 5.0.4 on 2026-03-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proxy_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ogrenci_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Öğrenci No'),
        ),
    ]
